name: Testing CI

on: pull_request

concurrency:
  group: "${{ github.workflow }} at ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 21
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - id: install-dependencies
        name: Install dependencies
        run: npm ci
      - id: test
        name: Test
        run: npm test
